<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\CountryEconomy;
use App\Models\CountryRisk;
use App\Models\CountryTradeStatistic;
use App\Models\CountryRegulation;
use App\Models\CountryRanking;
use App\Models\CountryOpportunity;
use App\Models\CountryTradeAgreement;
use Faker\Factory as Faker;

class CountryIntelligenceSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Faker::create();
        
        if (Country::count() === 0) {
            $baseCountries = [
                ['AF', 'Afghanistan', 'Asia', 'Kabul', 'AFN', 'Afghani', 38928000, '🇦🇫'],
                ['AL', 'Albania', 'Europe', 'Tirana', 'ALL', 'Lek', 2877800, '🇦🇱'],
                ['DZ', 'Algeria', 'Africa', 'Algiers', 'DZD', 'Dinar', 43851000, '🇩🇿'],
                ['AD', 'Andorra', 'Europe', 'Andorra la Vella', 'EUR', 'Euro', 77265, '🇦🇩'],
                ['AO', 'Angola', 'Africa', 'Luanda', 'AOA', 'Kwanza', 32866000, '🇦🇴'],
                ['AG', 'Antigua and Barbuda', 'Americas', 'St. John\'s', 'XCD', 'Dollar', 97928, '🇦🇬'],
                ['AR', 'Argentina', 'Americas', 'Buenos Aires', 'ARS', 'Peso', 45195000, '🇦🇷'],
                ['AM', 'Armenia', 'Asia', 'Yerevan', 'AMD', 'Dram', 2963000, '🇦🇲'],
                ['AU', 'Australia', 'Oceania', 'Canberra', 'AUD', 'Dollar', 25499000, '🇦🇺'],
                ['AT', 'Austria', 'Europe', 'Vienna', 'EUR', 'Euro', 8901000, '🇦🇹'],
                ['AZ', 'Azerbaijan', 'Asia', 'Baku', 'AZN', 'Manat', 10139000, '🇦🇿'],
                ['BS', 'Bahamas', 'Americas', 'Nassau', 'BSD', 'Dollar', 393248, '🇧🇸'],
                ['BH', 'Bahrain', 'Middle East', 'Manama', 'BHD', 'Dinar', 1701583, '🇧🇭'],
                ['BD', 'Bangladesh', 'Asia', 'Dhaka', 'BDT', 'Taka', 164689000, '🇧🇩'],
                ['BB', 'Barbados', 'Americas', 'Bridgetown', 'BBD', 'Dollar', 287371, '🇧🇧'],
                ['BY', 'Belarus', 'Europe', 'Minsk', 'BYN', 'Ruble', 9398861, '🇧🇾'],
                ['BE', 'Belgium', 'Europe', 'Brussels', 'EUR', 'Euro', 11589000, '🇧🇪'],
                ['BZ', 'Belize', 'Americas', 'Belmopan', 'BZD', 'Dollar', 397621, '🇧🇿'],
                ['BJ', 'Benin', 'Africa', 'Porto-Novo', 'XOF', 'Franc', 12123000, '🇧🇯'],
                ['BT', 'Bhutan', 'Asia', 'Thimphu', 'BTN', 'Ngultrum', 771612, '🇧🇹'],
                ['BO', 'Bolivia', 'Americas', 'Sucre', 'BOB', 'Boliviano', 11673000, '🇧🇴'],
                ['BA', 'Bosnia and Herzegovina', 'Europe', 'Sarajevo', 'BAM', 'Mark', 3280000, '🇧🇦'],
                ['BW', 'Botswana', 'Africa', 'Gaborone', 'BWP', 'Pula', 2351000, '🇧🇼'],
                ['BR', 'Brazil', 'Americas', 'Brasilia', 'BRL', 'Real', 212559000, '🇧🇷'],
                ['BN', 'Brunei', 'Asia', 'Bandar Seri Begawan', 'BND', 'Dollar', 437483, '🇧🇳'],
                ['BG', 'Bulgaria', 'Europe', 'Sofia', 'BGN', 'Lev', 6927000, '🇧🇬'],
                ['BF', 'Burkina Faso', 'Africa', 'Ouagadougou', 'XOF', 'Franc', 20903000, '🇧🇫'],
                ['BI', 'Burundi', 'Africa', 'Gitega', 'BIF', 'Franc', 11890000, '🇧🇮'],
                ['CV', 'Cabo Verde', 'Africa', 'Praia', 'CVE', 'Escudo', 555988, '🇨🇻'],
                ['KH', 'Cambodia', 'Asia', 'Phnom Penh', 'KHR', 'Riel', 16718000, '🇰🇭'],
                ['CM', 'Cameroon', 'Africa', 'Yaounde', 'XAF', 'Franc', 26545000, '🇨🇲'],
                ['CA', 'Canada', 'Americas', 'Ottawa', 'CAD', 'Dollar', 37742000, '🇨🇦'],
                ['CF', 'Central African Republic', 'Africa', 'Bangui', 'XAF', 'Franc', 4829000, '🇨🇫'],
                ['TD', 'Chad', 'Africa', 'N\'Djamena', 'XAF', 'Franc', 16425000, '🇹🇩'],
                ['CL', 'Chile', 'Americas', 'Santiago', 'CLP', 'Peso', 19116000, '🇨🇱'],
                ['CN', 'China', 'Asia', 'Beijing', 'CNY', 'Yuan', 1402112000, '🇨🇳'],
                ['CO', 'Colombia', 'Americas', 'Bogota', 'COP', 'Peso', 50882000, '🇨🇴'],
                ['KM', 'Comoros', 'Africa', 'Moroni', 'KMF', 'Franc', 869595, '🇰🇲'],
                ['CD', 'Congo (DRC)', 'Africa', 'Kinshasa', 'CDF', 'Franc', 89561000, '🇨🇩'],
                ['CG', 'Congo (Republic)', 'Africa', 'Brazzaville', 'XAF', 'Franc', 5518000, '🇨🇬'],
                ['CR', 'Costa Rica', 'Americas', 'San Jose', 'CRC', 'Colon', 5094000, '🇨🇷'],
                ['HR', 'Croatia', 'Europe', 'Zagreb', 'HRK', 'Kuna', 4047000, '🇭🇷'],
                ['CU', 'Cuba', 'Americas', 'Havana', 'CUP', 'Peso', 11326000, '🇨🇺'],
                ['CY', 'Cyprus', 'Europe', 'Nicosia', 'EUR', 'Euro', 1207000, '🇨🇾'],
                ['CZ', 'Czechia', 'Europe', 'Prague', 'CZK', 'Koruna', 10708000, '🇨🇿'],
                ['DK', 'Denmark', 'Europe', 'Copenhagen', 'DKK', 'Krone', 5831000, '🇩🇰'],
                ['DJ', 'Djibouti', 'Africa', 'Djibouti', 'DJF', 'Franc', 988000, '🇩🇯'],
                ['DM', 'Dominica', 'Americas', 'Roseau', 'XCD', 'Dollar', 71991, '🇩🇲'],
                ['DO', 'Dominican Republic', 'Americas', 'Santo Domingo', 'DOP', 'Peso', 10847000, '🇩🇴'],
                ['EC', 'Ecuador', 'Americas', 'Quito', 'USD', 'Dollar', 17643000, '🇪🇨'],
                ['EG', 'Egypt', 'Middle East', 'Cairo', 'EGP', 'Pound', 102334000, '🇪🇬'],
                ['SV', 'El Salvador', 'Americas', 'San Salvador', 'USD', 'Dollar', 6486000, '🇸🇻'],
                ['GQ', 'Equatorial Guinea', 'Africa', 'Malabo', 'XAF', 'Franc', 1402000, '🇬🇶'],
                ['ER', 'Eritrea', 'Africa', 'Asmara', 'ERN', 'Nakfa', 3546000, '🇪🇷'],
                ['EE', 'Estonia', 'Europe', 'Tallinn', 'EUR', 'Euro', 1331000, '🇪🇪'],
                ['SZ', 'Eswatini', 'Africa', 'Mbabane', 'SZL', 'Lilangeni', 1160000, '🇸🇿'],
                ['ET', 'Ethiopia', 'Africa', 'Addis Ababa', 'ETB', 'Birr', 114963000, '🇪🇹'],
                ['FJ', 'Fiji', 'Oceania', 'Suva', 'FJD', 'Dollar', 896444, '🇫🇯'],
                ['FI', 'Finland', 'Europe', 'Helsinki', 'EUR', 'Euro', 5530000, '🇫🇮'],
                ['FR', 'France', 'Europe', 'Paris', 'EUR', 'Euro', 67391582, '🇫🇷'],
                ['GA', 'Gabon', 'Africa', 'Libreville', 'XAF', 'Franc', 2225000, '🇬🇦'],
                ['GM', 'Gambia', 'Africa', 'Banjul', 'GMD', 'Dalasi', 2416000, '🇬🇲'],
                ['GE', 'Georgia', 'Asia', 'Tbilisi', 'GEL', 'Lari', 3714000, '🇬🇪'],
                ['DE', 'Germany', 'Europe', 'Berlin', 'EUR', 'Euro', 83240000, '🇩🇪'],
                ['GH', 'Ghana', 'Africa', 'Accra', 'GHS', 'Cedi', 31072000, '🇬🇭'],
                ['GR', 'Greece', 'Europe', 'Athens', 'EUR', 'Euro', 10715000, '🇬🇷'],
                ['GD', 'Grenada', 'Americas', 'St. George\'s', 'XCD', 'Dollar', 112519, '🇬🇩'],
                ['GT', 'Guatemala', 'Americas', 'Guatemala City', 'GTQ', 'Quetzal', 16858000, '🇬🇹'],
                ['GN', 'Guinea', 'Africa', 'Conakry', 'GNF', 'Franc', 13132000, '🇬🇳'],
                ['GW', 'Guinea-Bissau', 'Africa', 'Bissau', 'XOF', 'Franc', 1967000, '🇬🇼'],
                ['GY', 'Guyana', 'Americas', 'Georgetown', 'GYD', 'Dollar', 786559, '🇬🇾'],
                ['HT', 'Haiti', 'Americas', 'Port-au-Prince', 'HTG', 'Gourde', 11402000, '🇭🇹'],
                ['HN', 'Honduras', 'Americas', 'Tegucigalpa', 'HNL', 'Lempira', 9904000, '🇭🇳'],
                ['HU', 'Hungary', 'Europe', 'Budapest', 'HUF', 'Forint', 9749000, '🇭🇺'],
                ['IS', 'Iceland', 'Europe', 'Reykjavik', 'ISK', 'Krona', 366130, '🇮🇸'],
                ['IN', 'India', 'Asia', 'New Delhi', 'INR', 'Rupee', 1380004385, '🇮🇳'],
                ['ID', 'Indonesia', 'Asia', 'Jakarta', 'IDR', 'Rupiah', 273523615, '🇮🇩'],
                ['IR', 'Iran', 'Middle East', 'Tehran', 'IRR', 'Rial', 83992000, '🇮🇷'],
                ['IQ', 'Iraq', 'Middle East', 'Baghdad', 'IQD', 'Dinar', 40222000, '🇮🇶'],
                ['IE', 'Ireland', 'Europe', 'Dublin', 'EUR', 'Euro', 4994000, '🇮🇪'],
                ['IL', 'Israel', 'Middle East', 'Jerusalem', 'ILS', 'Shekel', 9216900, '🇮🇱'],
                ['IT', 'Italy', 'Europe', 'Rome', 'EUR', 'Euro', 59554000, '🇮🇹'],
                ['JM', 'Jamaica', 'Americas', 'Kingston', 'JMD', 'Dollar', 2961000, '🇯🇲'],
                ['JP', 'Japan', 'Asia', 'Tokyo', 'JPY', 'Yen', 125836021, '🇯🇵'],
                ['JO', 'Jordan', 'Middle East', 'Amman', 'JOD', 'Dinar', 10203000, '🇯🇴'],
                ['KZ', 'Kazakhstan', 'Asia', 'Nur-Sultan', 'KZT', 'Tenge', 18754000, '🇰🇿'],
                ['KE', 'Kenya', 'Africa', 'Nairobi', 'KES', 'Shilling', 53771000, '🇰🇪'],
                ['KI', 'Kiribati', 'Oceania', 'Tarawa', 'AUD', 'Dollar', 119446, '🇰🇮'],
                ['KP', 'North Korea', 'Asia', 'Pyongyang', 'KPW', 'Won', 25778000, '🇰🇵'],
                ['KR', 'South Korea', 'Asia', 'Seoul', 'KRW', 'Won', 51780000, '🇰🇷'],
                ['KW', 'Kuwait', 'Middle East', 'Kuwait City', 'KWD', 'Dinar', 4270000, '🇰🇼'],
                ['KG', 'Kyrgyzstan', 'Asia', 'Bishkek', 'KGS', 'Som', 6524000, '🇰🇬'],
                ['LA', 'Laos', 'Asia', 'Vientiane', 'LAK', 'Kip', 7275000, '🇱🇦'],
                ['LV', 'Latvia', 'Europe', 'Riga', 'EUR', 'Euro', 1901000, '🇱🇻'],
                ['LB', 'Lebanon', 'Middle East', 'Beirut', 'LBP', 'Pound', 6825000, '🇱🇧'],
                ['LS', 'Lesotho', 'Africa', 'Maseru', 'LSL', 'Loti', 2142000, '🇱🇸'],
                ['LR', 'Liberia', 'Africa', 'Monrovia', 'LRD', 'Dollar', 5057000, '🇱🇷'],
                ['LY', 'Libya', 'Africa', 'Tripoli', 'LYD', 'Dinar', 6871000, '🇱🇾'],
                ['LI', 'Liechtenstein', 'Europe', 'Vaduz', 'CHF', 'Franc', 38128, '🇱🇮'],
                ['LT', 'Lithuania', 'Europe', 'Vilnius', 'EUR', 'Euro', 2794000, '🇱🇹'],
                ['LU', 'Luxembourg', 'Europe', 'Luxembourg City', 'EUR', 'Euro', 632275, '🇱🇺'],
                ['MG', 'Madagascar', 'Africa', 'Antananarivo', 'MGA', 'Ariary', 27691000, '🇲🇬'],
                ['MW', 'Malawi', 'Africa', 'Lilongwe', 'MWK', 'Kwacha', 19129000, '🇲🇼'],
                ['MY', 'Malaysia', 'Asia', 'Kuala Lumpur', 'MYR', 'Ringgit', 32365000, '🇲🇾'],
                ['MV', 'Maldives', 'Asia', 'Male', 'MVR', 'Rufiyaa', 540542, '🇲🇻'],
                ['ML', 'Mali', 'Africa', 'Bamako', 'XOF', 'Franc', 20250000, '🇲🇱'],
                ['MT', 'Malta', 'Europe', 'Valletta', 'EUR', 'Euro', 514564, '🇲🇹'],
                ['MH', 'Marshall Islands', 'Oceania', 'Majuro', 'USD', 'Dollar', 59194, '🇲🇭'],
                ['MR', 'Mauritania', 'Africa', 'Nouakchott', 'MRU', 'Ouguiya', 4649000, '🇲🇷'],
                ['MU', 'Mauritius', 'Africa', 'Port Louis', 'MUR', 'Rupee', 1265000, '🇲🇺'],
                ['MX', 'Mexico', 'Americas', 'Mexico City', 'MXN', 'Peso', 128932000, '🇲🇽'],
                ['FM', 'Micronesia', 'Oceania', 'Palikir', 'USD', 'Dollar', 115021, '🇫🇲'],
                ['MD', 'Moldova', 'Europe', 'Chisinau', 'MDL', 'Leu', 2620000, '🇲🇩'],
                ['MC', 'Monaco', 'Europe', 'Monaco', 'EUR', 'Euro', 39244, '🇲🇨'],
                ['MN', 'Mongolia', 'Asia', 'Ulaanbaatar', 'MNT', 'Tugrik', 3278000, '🇲🇳'],
                ['ME', 'Montenegro', 'Europe', 'Podgorica', 'EUR', 'Euro', 621718, '🇲🇪'],
                ['MA', 'Morocco', 'Africa', 'Rabat', 'MAD', 'Dirham', 36910000, '🇲🇦'],
                ['MZ', 'Mozambique', 'Africa', 'Maputo', 'MZN', 'Metical', 31255000, '🇲🇿'],
                ['MM', 'Myanmar', 'Asia', 'Naypyidaw', 'MMK', 'Kyat', 54409000, '🇲🇲'],
                ['NA', 'Namibia', 'Africa', 'Windhoek', 'NAD', 'Dollar', 2540000, '🇳🇦'],
                ['NR', 'Nauru', 'Oceania', 'Yaren', 'AUD', 'Dollar', 10834, '🇳🇷'],
                ['NP', 'Nepal', 'Asia', 'Kathmandu', 'NPR', 'Rupee', 29136000, '🇳🇵'],
                ['NL', 'Netherlands', 'Europe', 'Amsterdam', 'EUR', 'Euro', 17441000, '🇳🇱'],
                ['NZ', 'New Zealand', 'Oceania', 'Wellington', 'NZD', 'Dollar', 5084000, '🇳🇿'],
                ['NI', 'Nicaragua', 'Americas', 'Managua', 'NIO', 'Cordoba', 6624000, '🇳🇮'],
                ['NE', 'Niger', 'Africa', 'Niamey', 'XOF', 'Franc', 24206000, '🇳🇪'],
                ['NG', 'Nigeria', 'Africa', 'Abuja', 'NGN', 'Naira', 206139000, '🇳🇬'],
                ['MK', 'North Macedonia', 'Europe', 'Skopje', 'MKD', 'Denar', 2083000, '🇲🇰'],
                ['NO', 'Norway', 'Europe', 'Oslo', 'NOK', 'Krone', 5379000, '🇳🇴'],
                ['OM', 'Oman', 'Middle East', 'Muscat', 'OMR', 'Rial', 5106000, '🇴🇲'],
                ['PK', 'Pakistan', 'Asia', 'Islamabad', 'PKR', 'Rupee', 220892000, '🇵🇰'],
                ['PW', 'Palau', 'Oceania', 'Ngerulmud', 'USD', 'Dollar', 18092, '🇵🇼'],
                ['PS', 'Palestine', 'Middle East', 'Jerusalem', 'ILS', 'Shekel', 5101000, '🇵🇸'],
                ['PA', 'Panama', 'Americas', 'Panama City', 'PAB', 'Balboa', 4314000, '🇵🇦'],
                ['PG', 'Papua New Guinea', 'Oceania', 'Port Moresby', 'PGK', 'Kina', 8947000, '🇵🇬'],
                ['PY', 'Paraguay', 'Americas', 'Asuncion', 'PYG', 'Guarani', 7132000, '🇵🇾'],
                ['PE', 'Peru', 'Americas', 'Lima', 'PEN', 'Sol', 32971000, '🇵🇪'],
                ['PH', 'Philippines', 'Asia', 'Manila', 'PHP', 'Peso', 109581000, '🇵🇭'],
                ['PL', 'Poland', 'Europe', 'Warsaw', 'PLN', 'Zloty', 37950000, '🇵🇱'],
                ['PT', 'Portugal', 'Europe', 'Lisbon', 'EUR', 'Euro', 10305000, '🇵🇹'],
                ['QA', 'Qatar', 'Middle East', 'Doha', 'QAR', 'Riyal', 2881000, '🇶🇦'],
                ['RO', 'Romania', 'Europe', 'Bucharest', 'RON', 'Leu', 19286000, '🇷🇴'],
                ['RU', 'Russia', 'Europe', 'Moscow', 'RUB', 'Ruble', 144104000, '🇷🇺'],
                ['RW', 'Rwanda', 'Africa', 'Kigali', 'RWF', 'Franc', 12952000, '🇷🇼'],
                ['KN', 'Saint Kitts and Nevis', 'Americas', 'Basseterre', 'XCD', 'Dollar', 53192, '🇰🇳'],
                ['LC', 'Saint Lucia', 'Americas', 'Castries', 'XCD', 'Dollar', 183629, '🇱🇨'],
                ['VC', 'Saint Vincent and the Grenadines', 'Americas', 'Kingstown', 'XCD', 'Dollar', 110947, '🇻🇨'],
                ['WS', 'Samoa', 'Oceania', 'Apia', 'WST', 'Tala', 198410, '🇼🇸'],
                ['SM', 'San Marino', 'Europe', 'San Marino', 'EUR', 'Euro', 33938, '🇸🇲'],
                ['ST', 'Sao Tome and Principe', 'Africa', 'Sao Tome', 'STN', 'Dobra', 219159, '🇸🇹'],
                ['SA', 'Saudi Arabia', 'Middle East', 'Riyadh', 'SAR', 'Riyal', 34813000, '🇸🇦'],
                ['SN', 'Senegal', 'Africa', 'Dakar', 'XOF', 'Franc', 16743000, '🇸🇳'],
                ['RS', 'Serbia', 'Europe', 'Belgrade', 'RSD', 'Dinar', 6908000, '🇷🇸'],
                ['SC', 'Seychelles', 'Africa', 'Victoria', 'SCR', 'Rupee', 98462, '🇸🇨'],
                ['SL', 'Sierra Leone', 'Africa', 'Freetown', 'SLL', 'Leone', 7976000, '🇸🇱'],
                ['SG', 'Singapore', 'Asia', 'Singapore', 'SGD', 'Dollar', 5685800, '🇸🇬'],
                ['SK', 'Slovakia', 'Europe', 'Bratislava', 'EUR', 'Euro', 5459000, '🇸🇰'],
                ['SI', 'Slovenia', 'Europe', 'Ljubljana', 'EUR', 'Euro', 2100000, '🇸🇮'],
                ['SB', 'Solomon Islands', 'Oceania', 'Honiara', 'SBD', 'Dollar', 686878, '🇸🇧'],
                ['SO', 'Somalia', 'Africa', 'Mogadishu', 'SOS', 'Shilling', 15893000, '🇸🇴'],
                ['ZA', 'South Africa', 'Africa', 'Pretoria', 'ZAR', 'Rand', 59308000, '🇿🇦'],
                ['SS', 'South Sudan', 'Africa', 'Juba', 'SSP', 'Pound', 11193000, '🇸🇸'],
                ['ES', 'Spain', 'Europe', 'Madrid', 'EUR', 'Euro', 47351000, '🇪🇸'],
                ['LK', 'Sri Lanka', 'Asia', 'Sri Jayawardenepura Kotte', 'LKR', 'Rupee', 21919000, '🇱🇰'],
                ['SD', 'Sudan', 'Africa', 'Khartoum', 'SDG', 'Pound', 43849000, '🇸🇩'],
                ['SR', 'Suriname', 'Americas', 'Paramaribo', 'SRD', 'Dollar', 586634, '🇸🇷'],
                ['SE', 'Sweden', 'Europe', 'Stockholm', 'SEK', 'Krona', 10353000, '🇸🇪'],
                ['CH', 'Switzerland', 'Europe', 'Bern', 'CHF', 'Franc', 8636000, '🇨🇭'],
                ['SY', 'Syria', 'Middle East', 'Damascus', 'SYP', 'Pound', 17500000, '🇸🇾'],
                ['TW', 'Taiwan', 'Asia', 'Taipei', 'TWD', 'Dollar', 23561000, '🇹🇼'],
                ['TJ', 'Tajikistan', 'Asia', 'Dushanbe', 'TJS', 'Somoni', 9537000, '🇹🇯'],
                ['TZ', 'Tanzania', 'Africa', 'Dodoma', 'TZS', 'Shilling', 59734000, '🇹🇿'],
                ['TH', 'Thailand', 'Asia', 'Bangkok', 'THB', 'Baht', 69799000, '🇹🇭'],
                ['TL', 'Timor-Leste', 'Asia', 'Dili', 'USD', 'Dollar', 1318000, '🇹🇱'],
                ['TG', 'Togo', 'Africa', 'Lome', 'XOF', 'Franc', 8278000, '🇹🇬'],
                ['TO', 'Tonga', 'Oceania', 'Nukuʻalofa', 'TOP', 'Paʻanga', 105697, '🇹🇴'],
                ['TT', 'Trinidad and Tobago', 'Americas', 'Port of Spain', 'TTD', 'Dollar', 1399000, '🇹🇹'],
                ['TN', 'Tunisia', 'Africa', 'Tunis', 'TND', 'Dinar', 11818000, '🇹🇳'],
                ['TR', 'Turkey', 'Middle East', 'Ankara', 'TRY', 'Lira', 84339000, '🇹🇷'],
                ['TM', 'Turkmenistan', 'Asia', 'Ashgabat', 'TMT', 'Manat', 6031000, '🇹🇲'],
                ['TV', 'Tuvalu', 'Oceania', 'Funafuti', 'AUD', 'Dollar', 11792, '🇹🇻'],
                ['UG', 'Uganda', 'Africa', 'Kampala', 'UGX', 'Shilling', 45741000, '🇺🇬'],
                ['UA', 'Ukraine', 'Europe', 'Kyiv', 'UAH', 'Hryvnia', 44134000, '🇺🇦'],
                ['AE', 'United Arab Emirates', 'Middle East', 'Abu Dhabi', 'AED', 'Dirham', 9890000, '🇦🇪'],
                ['GB', 'United Kingdom', 'Europe', 'London', 'GBP', 'Pound', 67215000, '🇬🇧'],
                ['US', 'United States', 'Americas', 'Washington, D.C.', 'USD', 'Dollar', 331002651, '🇺🇸'],
                ['UY', 'Uruguay', 'Americas', 'Montevideo', 'UYU', 'Peso', 3473000, '🇺🇾'],
                ['UZ', 'Uzbekistan', 'Asia', 'Tashkent', 'UZS', 'Som', 34232000, '🇺🇿'],
                ['VU', 'Vanuatu', 'Oceania', 'Port Vila', 'VUV', 'Vatu', 307150, '🇻🇺'],
                ['VA', 'Vatican City', 'Europe', 'Vatican City', 'EUR', 'Euro', 825, '🇻🇦'],
                ['VE', 'Venezuela', 'Americas', 'Caracas', 'VES', 'Bolivar', 28435000, '🇻🇪'],
                ['VN', 'Vietnam', 'Asia', 'Hanoi', 'VND', 'Dong', 97338000, '🇻🇳'],
                ['YE', 'Yemen', 'Middle East', 'Sana\'a', 'YER', 'Rial', 29825000, '🇾🇪'],
                ['ZM', 'Zambia', 'Africa', 'Lusaka', 'ZMW', 'Kwacha', 18383000, '🇿🇲'],
                ['ZW', 'Zimbabwe', 'Africa', 'Harare', 'ZWL', 'Dollar', 14862000, '🇿🇼'],
            ];

            foreach ($baseCountries as $c) {
                Country::create([
                    'iso_code' => $c[0],
                    'country_name' => $c[1],
                    'region' => $c[2],
                    'capital' => $c[3],
                    'currency_code' => $c[4],
                    'currency_name' => $c[5],
                    'population' => $c[6],
                    'flag' => $c[7],
                    'timezone' => 'UTC',
                    'latitude' => 0,
                    'longitude' => 0,
                    'language' => 'Native'
                ]);
            }
        }

        $countries = Country::all();
        
        foreach ($countries as $country) {
            // Update country with intelligence scores
            $country->update([
                'risk_score' => $faker->randomFloat(2, 10, 90),
                'opportunity_score' => $faker->randomFloat(2, 40, 95),
                'political_stability' => $faker->randomFloat(2, 30, 95),
                'trade_status' => $faker->randomElement(['Active', 'Restricted', 'Growing', 'Stable']),
            ]);

            CountryEconomy::create([
                'country_id' => $country->id,
                'gdp' => $faker->randomFloat(2, 1000000000, 20000000000000),
                'gdp_growth' => $faker->randomFloat(2, -2, 8),
                'inflation_rate' => $faker->randomFloat(2, 0, 15),
                'interest_rate' => $faker->randomFloat(2, 0, 10),
                'exchange_rate' => $faker->randomFloat(6, 0.5, 150),
                'unemployment_rate' => $faker->randomFloat(2, 2, 20),
                'consumer_price_index' => $faker->randomFloat(2, 90, 150),
                'producer_price_index' => $faker->randomFloat(2, 90, 150),
                'purchasing_power' => $faker->randomFloat(2, 1000, 70000),
                'year' => date('Y'),
            ]);

            CountryRisk::create([
                'country_id' => $country->id,
                'political_risk' => $faker->randomFloat(2, 0, 100),
                'economic_risk' => $faker->randomFloat(2, 0, 100),
                'natural_disaster_risk' => $faker->randomFloat(2, 0, 100),
                'war_risk' => $faker->randomFloat(2, 0, 100),
                'trade_restriction_risk' => $faker->randomFloat(2, 0, 100),
                'currency_risk' => $faker->randomFloat(2, 0, 100),
                'supply_chain_risk' => $faker->randomFloat(2, 0, 100),
                'overall_risk_score' => $faker->randomFloat(2, 0, 100),
                'last_calculated_at' => now(),
            ]);

            CountryTradeStatistic::create([
                'country_id' => $country->id,
                'total_import' => $faker->randomFloat(2, 500000000, 500000000000),
                'total_export' => $faker->randomFloat(2, 500000000, 500000000000),
                'trade_balance' => $faker->randomFloat(2, -10000000000, 10000000000),
                'import_duty_avg' => $faker->randomFloat(2, 0, 20),
                'export_duty_avg' => $faker->randomFloat(2, 0, 10),
                'top_imported_commodities' => json_encode([$faker->word, $faker->word, $faker->word]),
                'top_exported_commodities' => json_encode([$faker->word, $faker->word, $faker->word]),
                'main_trade_partners' => json_encode([$faker->countryCode, $faker->countryCode]),
                'year' => date('Y'),
            ]);

            CountryRegulation::create([
                'country_id' => $country->id,
                'regulation_type' => 'Import Tariff',
                'description' => $faker->sentence,
                'severity' => $faker->randomElement(['High', 'Medium', 'Low']),
                'effective_date' => now()->subDays(rand(1, 365)),
            ]);

            CountryRanking::create([
                'country_id' => $country->id,
                'logistics_performance_index' => $faker->randomFloat(2, 1, 5),
                'ease_of_doing_business' => $faker->randomFloat(2, 0, 100),
                'corruption_perception_index' => $faker->randomFloat(2, 0, 100),
                'human_development_index' => $faker->randomFloat(2, 0.5, 1),
                'shipping_accessibility_rank' => $faker->numberBetween(1, 190),
                'year' => date('Y'),
            ]);

            CountryOpportunity::create([
                'country_id' => $country->id,
                'demand_growth' => $faker->randomFloat(2, -5, 20),
                'import_opportunity_score' => $faker->randomFloat(2, 0, 100),
                'export_opportunity_score' => $faker->randomFloat(2, 0, 100),
                'market_size' => $faker->randomFloat(2, 1000000000, 100000000000),
                'market_growth' => $faker->randomFloat(2, 0, 15),
                'competitor_level' => $faker->randomElement(['High', 'Medium', 'Low']),
                'expected_profit_margin' => $faker->randomFloat(2, 5, 30),
                'recommended_commodities' => json_encode([$faker->word, $faker->word]),
                'overall_opportunity_score' => $faker->randomFloat(2, 0, 100),
                'last_calculated_at' => now(),
            ]);

            CountryTradeAgreement::create([
                'country_id' => $country->id,
                'agreement_name' => $faker->company . ' Free Trade Agreement',
                'partner_countries' => 'Global',
                'status' => 'Active',
                'signed_date' => now()->subYears(rand(1, 10)),
            ]);
        }
    }
}
